version: 2

sources:
  - name: asana
    schema: "sources"
    meta:
      external_location: "/home/uptown/Projects/panfactum/reference-infrastructure/services/bi/data/asana/{name}/*.jsonl"
    tables:
      - name: custom_fields
      - name: portfolios
      - name: portfolios_compact
      - name: portfolios_memberships
      - name: projects
      - name: tasks
      - name: users
      - name: workspaces

  - name: stripe
    schema: "sources"
    meta:
      external_location: "/home/uptown/Projects/panfactum/reference-infrastructure/services/bi/data/stripe/{name}/*.jsonl"
    tables:
      - name: balance_transactions
      - name: charges
      - name: customer_balance_transactions
      - name: customers
      - name: events
      - name: external_account_bank_accounts
      - name: invoices
      - name: payment_intents
      - name: payment_methods
      - name: plans
      - name: prices
      - name: products
      - name: setup_intents
      - name: subscription_items
      - name: subscription_schedule
      - name: subscriptions
      - name: usage_records

  - name: gsheet
    schema: "gsheet"
    tables:
      - name: gross_margin
        meta:
          plugin: gsheet # Explicitly declare the plugin
          url: "https://docs.google.com/spreadsheets/d/1KsC-tBeyBi2oYS0xLmARGA-g1INDlhU4ZW1dZmjLOcw/edit#gid=0"
          worksheet: 0
