models:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: ../bi.duckdb  # Path relative to the profile
      schema: 'pf'
      extensions:
        - httpfs
        - parquet
      plugins:
        - module: gsheet
          config:
            method: oauth
